FROM golang:1.11

RUN export GOPATH=/go/src/github.com/jordanlanch/postAMQP_Sql
RUN mkdir -p /go/src/github.com/jordanlanch/postAMQP_Sql
WORKDIR /go/src/github.com/jordanlanch/postAMQP_Sql

COPY main.go main.go

RUN go get github.com/streadway/amqp/...
RUN go build -o main .
RUN ls 

CMD  ["go","run", "main"]