FROM golang:1.11

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" \
    && chmod -R 777 "$GOPATH"
RUN mkdir -p /go/src/readApi
WORKDIR /go/src/readApi
COPY main.go main.go

RUN go build -o main .
RUN ls 

CMD ["go", "run", "main.go"]