FROM golang:1.11

RUN export GOPATH=/go/src/github.com/jordanlanch/postAMQP_Sql_Docker
RUN mkdir -p /go/src/github.com/jordanlanch/postAMQP_Sql_Docker
WORKDIR /go/src/github.com/jordanlanch/postAMQP_Sql_Docker

COPY main.go main.go

RUN go get github.com/streadway/amqp/...
RUN go build -o main .
RUN ls 

CMD  ["go","run", "main"]