FROM golang:1.11

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" \
    && chmod -R 777 "$GOPATH"
RUN mkdir -p /go/src/phoenix
WORKDIR /go/src/phoenix
COPY main.go main.go

RUN go get github.com/streadway/amqp/...
RUN go get github.com/jinzhu/gorm/...
RUN go get golang.org/x/crypto/bcrypt/...

RUN go build -o main .
RUN ls 

CMD ["go", "run", "main.go"]

EXPOSE 8080